### ISSUE TITLE
python get_sessions.py not working with SPP 10.1.2

### ISSUE THREAD

**Issue by tirili** [sppautomation/sppclient#1]
Hello,

using Spectrum Protect Plus 10.1.1, I was able to get all session/job information for the last 20 hrs using

 python get_sessions.py <tiri-SPP-Server> <user> <password> 20

The current version does not contain get_sessions.py, and the former does not work with SPP 10.1.2.

Any help is appreciated.

Best regards, and thanks for this great script!
Thomas

**Comment by benjones917** [comment]
Hi Thomas,

Thanks for bringing this to my attention... will get a new version into the repo which is compatible with 10.1.2 and Python3

**Comment by benjones917** [comment]
Hi Thomas, a new get_sessions.py has been uploaded... this one uses the optparse module that is in our other samples.. so command syntax is a little different:
python3 get_sessions.py --user=admin --pass=password123 --host="https://172.20.49.50" --timeframe=24

**Comment by tirili** [comment]
What am I missing?

git clone https://github.com/sppautomation/sppclient.git
cd sppclient/samples/
python get_sessions.py --host="10.XX" --user="admin" --pass='XX!' 
--timeframe=20

Traceback (most recent call last):
   File "get_sessions.py", line 1, in <module>
     import requests
ImportError: No module named requests

Any help is appreciated.

Best regards,
Thomas

Am 2018-11-29 21:33, schrieb Ben Jones:

**Comment by tirili** [comment]
Using python3 does not work either:

Traceback (most recent call last):
   File "get_sessions.py", line 91, in <module>
     run()
   File "get_sessions.py", line 85, in run
     sessionid = get_spp_sessionid()
   File "get_sessions.py", line 30, in get_spp_sessionid
     r = requests.post(url, verify=False, 
auth=HTTPBasicAuth(options.username, options.password))
   File "/usr/lib/python3.4/site-packages/requests/api.py", line 112, in 
post
     return request('post', url, data=data, json=json, **kwargs)
   File "/usr/lib/python3.4/site-packages/requests/api.py", line 58, in 
request
     return session.request(method=method, url=url, **kwargs)
   File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 
498, in request
     prep = self.prepare_request(req)
   File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 
441, in prepare_request
     hooks=merge_hooks(request.hooks, self.hooks),
   File "/usr/lib/python3.4/site-packages/requests/models.py", line 309, 
in prepare
     self.prepare_url(url, params)
   File "/usr/lib/python3.4/site-packages/requests/models.py", line 383, 
in prepare_url
     raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 
'10.XX/api/endeavour/session': No schema supplied. Perhaps you meant 
http://XX/api/endeavour/session?


Am 2018-11-29 21:33, schrieb Ben Jones:

**Comment by benjones917** [comment]
Hi Thomas,

The first error indicates you're missing the "requests" module from the Python installation you're trying to run it from. The newer releases of sppclient are Python3 so make sure that's what you're using.

In that second error (using Python3) it looks like requests is installed but url is malformed. Make sure you prefix the --host argument with "https://"

**Comment by tirili** [comment]
Hey cool!
Thank you. Now it works :)

Best regards
Thomas


Am 2018-11-30 14:32, schrieb Ben Jones:
