### ISSUE TITLE
Local problem

### ISSUE THREAD

**Issue by demetr88** [sppautomation/sppclient#4]
How to get association VMs to policy? I can't understand right Rest-Request .
And exists extended manual about Rest  except standard API from SPP package?
Dmitry

**Comment by benjones917** [comment]
@demetr88 apologies for the very late response here... there are a couple of ways to get this information, the best is probably use the /api/hypervisor endpoints ... you can get by ID or searching by name:
```
vminfo = client.SppAPI(session, 'corehv').get(path="/<hypervisor_id>/vm/<vm_id>?from=hlo")
or
searchdata = {"name":'<vm_name>',"hypervisorType":"*"}
vmsearch = client.SppAPI(session, 'corehv').post(path="/search?resourceType=vm&from=hlo", data=searchdata)['vms']
```

as of 10.1.6 there is a newer version of the API guide included with Spectrum Protect Plus which is more comprehensive and up to date
