### ISSUE TITLE
get_alerts.py read from file

### ISSUE THREAD

**Issue by torber-sys** [sppautomation/sppclient#5]
I get errors when using -a switch:

python3 getalerts.py -a
Traceback (most recent call last):
  File "getalerts.py", line 156, in <module>
    main()
  File "getalerts.py", line 136, in main
    params_from_file = spputil.read_params_from_file(filename="auth.txt")
AttributeError: module 'spplib.cli.util' has no attribute 'read_params_from_file'

I wander if maybe spplib.cli.util is not updated with the new switch.

**Comment by benjones917** [comment]
@torber-sys appologies for the late response ... this seems to be working for me using latest version of sppclient ... please re-open if still an issue

```
$ python3 get_alerts.py -a "auth.txt" --timeframe=10

     last occurance   | Type   | ackn  | description
  ------------------------------------------------------------------------------------------------------------------------
  2021-03-31 04:17:41 | WARN   | False | Job Hypervisor Inventory (id=1003, session=1,617,177,600,149) partially succeeded.
```
