### ISSUE TITLE
pip modules are outdated

### ISSUE THREAD

**Issue by SupremeGit** [sppautomation/sppclient#7]
I've just wasted days fixing bugs in the code installed by pip, only to find the stuff in latest zipfile is way newer.

Please update the pip modules.

**Comment by SupremeGit** [comment]
I mean, SERIOUSLY OUTDATED.

the cli/util.py currently in pip does not even have the fixes for Python 3.7 that were committed TWO YEARS AGO.

If you aren't going to maintain the pip modules on PyPi, remove them, and don't mention them.

**Comment by SupremeGit** [comment]
Even the version number in the PyPi modules (0.58) is the same as in the latest commits.
But the PyPi stuff is ancient. It is very misleading, and wasted a bunch of my time, which would'dve been much better spent getting to grips with the latest versions of the code, because the new stuff does seem good.

**Comment by benjones917** [comment]
@SupremeGit  I went ahead and pushed the current version of the repository to PyPI as version 0.60 ... let me know if any issues with it

**Comment by SupremeGit** [comment]
Aaah sweet TY Ben, I've just installed new pip modules, and allis clar. Sorry if i sounded a bit grumpy before, i was pulling my hair out in pain and anguish when i discovered i wasn't working with latest version of your code, but happy now :-)
